calories_book_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('recipes/', include('recipes.urls')),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from . import views

from recipes.views import MyRecipeListView

urlpatterns = [
    path('profile/edit/', views.ProfileUpdate.as_view(), name='profile_edit'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('my_recipes/', MyRecipeListView.as_view(), name='users_recipe'),
]

recipes/models.py
from django.db import models
from django.contrib.auth import get_user_model

from django.urls import reverse

from django.utils.timezone import now


class Ingredient(models.Model):
    name = models.CharField(max_length=30)
    proteins = models.FloatField()
    fats = models.FloatField()
    carbohydrates = models.FloatField()

    def __str__(self):
        return self.name


class IngredientItem(models.Model):
    ingredient = models.ForeignKey(Ingredient,
                                   on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()

    def __str__(self):
        return self.ingredient.name

class Recipe(models.Model):
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True)
    ingredients = models.ManyToManyField(IngredientItem)
    title = models.CharField(max_length=50, verbose_name='Назва рецепту')
    pub_date = models.DateTimeField(default=now, editable=False)
    description = models.TextField(verbose_name='Опис')
    likes = models.ManyToManyField(get_user_model(), related_name='recipe_likes')

    @property
    def total_likes(self):
        return self.likes.count()

    @property
    def total_weight(self):
        total = 0.0
        for ingredient in self.ingredients.all():
            total += ingredient.quantity
        return total

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('recipe_detail', args=[str(self.id)])


class Comment(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='comments')
    text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(default=now, editable=False)
    author = models.ForeignKey(
        get_user_model(),
        on_delete = models.CASCADE,
    )

    def __str__(self):
        return self.text

templates/add_comment.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h1>Залишіть коментар</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success" type="submit">Зберегти</button>
  </form>
{% endblock content %}

templates/add_ingredient.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h1>Додайте новий інгредієнт в список інгредієнтів</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success" type="submit">Зберегти</button>
  </form>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Книга Калорій{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'home' %}"><h2>Книга калорій</h2></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'profile' %}"><h5>Профіль</h5><span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'top_recipe' %}"><h5>Топ рецептів</h5></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'users_recipe' %}"><h5>Мої рецепти</h5></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'recipe_list' %}"><h5>Останні рецепти</h5></a>
      </li>

        <form class="form-inline my-2 my-lg-0" action="{% url 'search' %}">
          <input class="form-control mr-sm-2" type="search" name="search" placeholder="Search" aria-label="Search"/>
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Знайти</button>
        </form>
      {% if request.user.is_superuser %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'add_ingredient' %}"><h5>Додати інгредієнт</h5></a>
      </li>
      {% endif %}

    </ul>
    <ul class="nav navbar-nav ml-auto">
      <li class="nav=item dropdown">
        <a href="#" class="nav-ling dropdown-toggle" data-toggle="dropdown">{{ user.userprofile.username }}</a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a href="{% url 'profile' %}" class="dropdown-item">Профіль</a>
          <a href="{% url 'users_recipe' %}" class="dropdown-item">Рецепти</a>
          <a href="{% url 'recipe_new' %}" class="dropdown-item">Додати рецепт</a>
          <div class="dropdown-divider"></div>
          <a href="{% url 'logout' %}" class="dropdown-item">Вийти</a>
        </div>
      </li>
    </ul>
  </div>
  </nav>
  <main>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  </main>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Головна сторінка{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class="row justify-content-md-center">
  <div class="col-md-auto">
    <p class="h5">Привіт, {{user.userprofile.username}}!</p>
    <a href="{% url 'logout' %}">Вийти</a>
    <a href="{% url 'profile' %}">Профіль</a>
  </div>
</div>
{% else %}
<div class="row justify-content-md-center">
  <div class="col-md-auto">
    <p class="h5">Ти не зареєстрований</p>
    <a href="{% url 'login' %}">Увійти</a>
    <a href="{% url 'signup' %}">Зареєструватись</a>
  </div>
</div>
{% endif %}
{% endblock %}

templates/profile.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Профіль користувача {{user.userprofile.username}}{% endblock %}

{% block content %}
<h1 class="text-center">Профіль користувача {{user.userprofile.username}}</h1>
<div class="container">
  <div class="row mt-5">
    <div class="col-sm mt-auto ml-auto mb-auto">
      {% if user.userprofile.image %}
      <div class="cropPhoto">
        <img class="img-fluid mb-2 mt-auto" src="{{ user.userprofile.image.url }}">
      </div>
      {% else %}
        <img src="/media/default-avatar.png" width="240">
      {% endif %}
    </div>
    <form class="col-sm-8 mt-auto mb-auto">
      <!-- TEXT FIELD GROUPS -->
      <div class="form-group row">
        <label for="name" class="col-sm-2 col-form-label">Нікнейм</label>
        <div class="col-sm-10">
          <input class="form-control" type="text" id="name" placeholder="{{user.userprofile.username}}" readonly>
        </div>
      </div>
      <div class="form-group row">
        <label for="name" class="col-sm-2 col-form-label">Ім'я</label>
        <div class="col-sm-10">
          <input class="form-control" type="text" id="name" placeholder="{{user.userprofile.first_name}}" readonly>
        </div>
      </div>
      <div class="form-group row">
        <label for="name" class="col-sm-2 col-form-label">Прізвище</label>
        <div class="col-sm-10">
          <input class="form-control" type="text" id="name" placeholder="{{user.userprofile.last_name}}" readonly>
        </div>
      </div>
      <div class="form-group row">
        <label for="email" class="col-sm-2 col-form-label">Email адреса</label>
        <div class="col-sm-10">
          <input class="form-control form-control-lg" type="email" id="email" placeholder="{{user.email}}" readonly>
          <small class="form-text text-muted">Ваша пошта використовується виключно для входу</small>
        </div>
      </div>
      <div class="form-group row">
        <label for="exampleFormControlTextarea1" class="col-sm-2 col-form-label">Біо</label>
        <div class="col-sm-10">
          <textarea class="form-control" id="exampleFormControlTextarea1" rows="5" style="resize:none" placeholder="{{user.userprofile.bio}}" readonly></textarea>
        </div>
      </div>
    </form>
  </div>
  <div class="row justify-content-md-center mt-auto">
    <div class="col col-lg-auto">
      <p><a href="{% url 'profile_edit' %}"><h6>Редагувати</h6></a></p>
    </div>
    <div class="col col-lg-auto">
      <p><a href="{% url 'home' %}"><h6>Назад</h6></a></p>
    </div>
  </div>
</div>

<style>
    .cropPhoto{
        overflow:hidden;
        width:250px;
        height:300px;
        display:block;
    }
</style>
{% endblock %}

templates/profile_edit.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Профіль користувача {{user.userprofile.username}}{% endblock %}

{% block content %}
  <h1>Редагування профілю</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Зберегти">
  </form>
{% endblock %}

templates/recipe_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h1 class="text-center">{{ object.title }}</h1>
    <p ><h4 class="text-center">by {{ object.author }} | {{ object.pub_date }}</h4></p>
    <p>{{ object.description }}</p>
  {% if user == recipe.author %}
    <p><a href="{% url 'recipe_edit' recipe.pk %}">Редагувати</a> |
      <a href="{% url 'recipe_delete' recipe.pk %}">Видалити</a></p>
  {% endif %}
    <p>Повернутись до <a href="{% url 'recipe_list' %}">Всіх рецептів</a>.</p>
    <hr>
    <form action="{% url 'like_recipe' recipe.pk %}" method="post">
      {% csrf_token %}
      <button type="submit" name="recipe_id",
      value="{{ recipe.id }}", class="btn btn-primary
      btn">{{ total_likes }} Лайків</button>
    </form>
</div>

{% endblock content %}

templates/recipe_edit.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h1>Редагування</h1>
  <form action="" method="post">{% csrf_token %}
    {{ form.title|crispy }}
  <button class="btn btn-info ml-2" type="submit">Обновити</button>
</form>
{% endblock content %}

templates/recipe_list.html
{% extends 'base.html' %}

{% block title %}Рецепти{% endblock %}

{% block content %}
  {% for recipe in object_list %}
  <div class="card mt-4 mb-auto">
    <div class="card-header">
      <span class="font-weight-bold">{{ recipe.title }}</span> &middot;
      <span class="text-muted">by {{ recipe.author }} |
      {{ recipe.pub_date }} | {{ recipe.total_likes }} Лайків | <a href="{% url 'recipe_detail' recipe.pk %}">Переглянути детальніше</a></span>
    </div>
    <div class="card-body">
      <p>{{ recipe.description }}</p>
      {% if request.user == recipe.author %}
        <p><a href="{% url 'recipe_edit' recipe.pk %}">Редагувати</a> |
          <a href="{% url 'recipe_delete' recipe.pk %}">Видалити</a></p>
      {% endif %}
      <form action="{% url 'like_recipe' recipe.pk %}" method="post">
        {% csrf_token %}
        <button type="submit" name="recipe_id",
        value="{{ recipe.id }}", class="btn btn-primary
        btn">{{ recipe.total_likes }} Лайків</button>
      </form>
    </div>
    <div class="card-footer">
      <a href="{% url 'add_comment' recipe.pk %}">Залишити коментар</a>
      <br>
        {% for comment in recipe.comments.all %}
        <hr>
        <div class="row mt-auto">
          <div class="col-md-1 mt-auto ml-auto mb-auto mr-auto">
            {% if comment.author.userprofile.image %}
              <img class="crop mb-auto rounded-circle" src="{{ comment.author.userprofile.image.url }}" height="90">
            {% else %}
              <img src="/media/default-avatar.png" width="240">
            {% endif %}
          </div>
          <div class="col-md-10 ml-1 mt-auto mb-auto mr-auto">
            <div class="card">
              <div class="card-header">
                <span class="text-muted">{{comment.pub_date}}</span>
              </div>
              <div class="card-body">
                <p>
                <span class="font-weight-bold">{{ comment.author.userprofile.username }} &middot;</span>
                {{ comment }}
                </p>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
    </div>
  </div>

  <style>
      .crop{
          overflow:hidden;
          width:100px;
          height:100px;
          display:block;
          border-style:solid;
          border-width:1px;
      }
  </style>
  {% endfor %}
{% endblock content %}

templates/recipe_new.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <h1>Новий рецепт</h1>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success" type="submit">Зберегти</button>
  </form>
{% endblock content %}

templates/search.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}

{% if ingredients %}
{% for ingredient in ingredients %}
  <div class="container">
    <div class="row justify-content-md-center">
      <p><h3>Назва: {{ingredient.name}}</h3></p>
    </div>
    <div class="row justify-content-md-center">
      <p><h4>Білки: {{ingredient.proteins}}|</h4></p>
      <p><h4>Жири: {{ingredient.fats}}|</h4></p>
      <p><h4>Вуглеводи: {{ingredient.carbohydrates}}</h4></p>
    </div>
  </div>
{% endfor %}
{% else %}
  <p>Ми не знайшли те, що ви шукали {{user.userprofile.username}}.</p>
  {% for object in ingredient %}
  <p>{{object.name}}</p>
  {% endfor %}
{% endif %}

{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Реєстрація{% endblock %}

{% block content %}
<h1>Реєстрація</h1>
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <button type="submit">Зареєструватись</button>
</form>
{% endblock %}

templates/top_recipe.html
{% extends 'base.html' %}

{% block title %}Рецепти{% endblock %}

{% block content %}
  {% for recipe in object_list %}
  <div class="card mt-4 mb-auto">
    <div class="card-header">
      <span class="font-weight-bold">{{ recipe.title }}</span> &middot;
      <span class="text-muted">by {{ recipe.author }} |
      {{ recipe.pub_date }} | {{ recipe.total_likes }} Лайків | <a href="{% url 'recipe_detail' recipe.pk %}">Переглянути детальніше</a></span>
    </div>
    <div class="card-body">
      <p>{{ recipe.description }}</p>
      {% if request.user == recipe.author %}
        <p><a href="{% url 'recipe_edit' recipe.pk %}">Редагувати</a> |
          <a href="{% url 'recipe_delete' recipe.pk %}">Видалити</a></p>
      {% endif %}
      <form action="{% url 'like_recipe' recipe.pk %}" method="post">
        {% csrf_token %}
        <button type="submit" name="recipe_id",
        value="{{ recipe.id }}", class="btn btn-primary
        btn">{{ recipe.total_likes }} Лайків</button>
      </form>
    </div>
    <div class="card-footer">
      <a href="{% url 'add_comment' recipe.pk %}">Залишити коментар</a>
      <br>
        {% for comment in recipe.comments.all %}
        <hr>
        <div class="row mt-auto">
          <div class="col-md-1 mt-auto ml-auto mb-auto mr-auto">
            {% if comment.author.userprofile.image %}
              <img class="crop mb-auto rounded-circle" src="{{ comment.author.userprofile.image.url }}">
            {% else %}
              <img src="/media/default-avatar.png" width="240">
            {% endif %}
          </div>
          <div class="col-md-10 ml-1 mt-auto mb-auto mr-auto">
            <div class="card">
              <div class="card-header">
                <span class="text-muted">{{comment.pub_date}}</span>
              </div>
              <div class="card-body">
                <p>
                <span class="font-weight-bold">{{ comment.author.userprofile.username }} &middot;</span>
                {{ comment }}
                </p>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
    </div>
  </div>
  <style>
      .crop{
          overflow:hidden;
          width:100px;
          height:100px;
          display:block;
          border-style:solid;
          border-width:1px;
      }
  </style>
  {% endfor %}
{% endblock content %}

templates/users_recipe.html
{% extends 'base.html' %}

{% block title %}Рецепти{% endblock %}

{% block content %}
<div class="row justify-content-md-center mt-4">
  <a href="{% url 'recipe_new' %}"><h4>Додати рецепт</h4></a>
</div>
  {% for recipe in object_list %}
  <div class="card mt-4 mb-auto">
    <div class="card-header">
      <span class="font-weight-bold">{{ recipe.title }}</span> &middot;
      <span class="text-muted">by {{ recipe.author }} |
      {{ recipe.pub_date }}</span>
    </div>
    <div class="card-body">
      <p>{{ recipe.description }}</p>
      {% if request.user == recipe.author %}
        <p><a href="{% url 'recipe_edit' recipe.pk %}">Редагувати</a> |
          <a href="{% url 'recipe_delete' recipe.pk %}">Видалити</a></p>
      {% endif %}
      <form action="{% url 'like_recipe' recipe.pk %}" method="post">
        {% csrf_token %}
        <button type="submit" name="recipe_id",
        value="{{ recipe.id }}", class="btn btn-primary
        btn">{{ recipe.total_likes }} Лайків</button>
      </form>
    </div>
    <div class="card-footer">
      {% if not recipe.comments.all %}
        <a href="{% url 'add_comment' recipe.pk %}">Залишити коментар</a>
      {% else %}
      <a href="{% url 'add_comment' recipe.pk %}">Залишити коментар</a>
      <br>
        {% for comment in recipe.comments.all %}
        <hr>
        <div class="row mt-auto">
          <div class="col-md-1 mt-auto ml-auto mb-auto">
            {% if comment.author.userprofile.image %}
              <img class="mb-auto rounded-circle" src="{{ comment.author.userprofile.image }}" height="90">
            {% else %}
              <img src="/media/default-avatar.png" width="240">
            {% endif %}
          </div>
          <div class="col-md-10 ml-auto mt-auto mb-auto mr-auto">
            <div class="card">
              <div class="card-header">
                <span class="text-muted">{{comment.pub_date}}</span>
              </div>
              <div class="card-body">
                <p>
                <span class="font-weight-bold">{{ comment.author.userprofile.username }} &middot;</span>
                {{ comment }}
                </p>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      {% endif %}
    </div>
  </div>
  {% endfor %}
{% endblock content %}